---
deployment:
  tasks:
    - export NODE_ENV=production
    - /opt/cpanel/ea-nodejs20/bin/npm install --legacy-peer-deps > npm-install.log 2>&1
    - /opt/cpanel/ea-nodejs20/bin/npm run build > npm-build.log 2>&1
